### ISSUE TITLE
怎么感觉很卡呀

### ISSUE THREAD

**Issue by Mrkk1** [Pong-lei/su7_imitate#1]

**Comment by Pong-lei** [comment]
加了reflect反射，比较吃性能，其次模型上的材质都是物理材质，也吃性能。如果建模时使用标准材质，帧数会高很多

修改材质前
![image](https://github.com/Pong-lei/su7_imitate/assets/57822607/1abedd24-be2d-4339-8adc-cba49c254600)
修改材质后
![code](https://github.com/Pong-lei/su7_imitate/assets/57822607/0029e1cf-a3d8-41e7-afd2-a59dfd8fcc23)
![image](https://github.com/Pong-lei/su7_imitate/assets/57822607/84174e30-53d2-4271-8053-56eb4fe63cdc)

**Comment by Pong-lei** [comment]
最新的代码，对反射做了优化，公司电脑已经可以到40fps啦~~~~
